W0806 16:07:47.437000 133220737298880 torch/distributed/run.py:757] 
W0806 16:07:47.437000 133220737298880 torch/distributed/run.py:757] *****************************************
W0806 16:07:47.437000 133220737298880 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0806 16:07:47.437000 133220737298880 torch/distributed/run.py:757] *****************************************
Traceback (most recent call last):
  File "/home/hslee/Desktop/Backbone-Neck_Self-Distillation/RT-DETR/tools/train.py", line 9, in <module>
    import src.misc.dist as dist 
  File "/home/hslee/Desktop/Backbone-Neck_Self-Distillation/RT-DETR/tools/../src/__init__.py", line 2, in <module>
    from . import data 
  File "/home/hslee/Desktop/Backbone-Neck_Self-Distillation/RT-DETR/tools/../src/data/__init__.py", line 2, in <module>
    from .coco import *
  File "/home/hslee/Desktop/Backbone-Neck_Self-Distillation/RT-DETR/tools/../src/data/coco/__init__.py", line 1, in <module>
    from .coco_dataset import (
  File "/home/hslee/Desktop/Backbone-Neck_Self-Distillation/RT-DETR/tools/../src/data/coco/coco_dataset.py", line 14, in <module>
    from torchvision import datapoints
ImportError: cannot import name 'datapoints' from 'torchvision' (/home/hslee/.local/lib/python3.10/site-packages/torchvision/__init__.py)
Traceback (most recent call last):
  File "/home/hslee/Desktop/Backbone-Neck_Self-Distillation/RT-DETR/tools/train.py", line 9, in <module>
    import src.misc.dist as dist 
  File "/home/hslee/Desktop/Backbone-Neck_Self-Distillation/RT-DETR/tools/../src/__init__.py", line 2, in <module>
    from . import data 
  File "/home/hslee/Desktop/Backbone-Neck_Self-Distillation/RT-DETR/tools/../src/data/__init__.py", line 2, in <module>
    from .coco import *
  File "/home/hslee/Desktop/Backbone-Neck_Self-Distillation/RT-DETR/tools/../src/data/coco/__init__.py", line 1, in <module>
    from .coco_dataset import (
  File "/home/hslee/Desktop/Backbone-Neck_Self-Distillation/RT-DETR/tools/../src/data/coco/coco_dataset.py", line 14, in <module>
    from torchvision import datapoints
ImportError: cannot import name 'datapoints' from 'torchvision' (/home/hslee/.local/lib/python3.10/site-packages/torchvision/__init__.py)
E0806 16:07:52.446000 133220737298880 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 1816567) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/hslee/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/hslee/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/hslee/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/hslee/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/hslee/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hslee/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-06_16:07:52
  host      : ada
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1816568)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-06_16:07:52
  host      : ada
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1816567)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
