/home/hslee/anaconda3/envs/DL/lib/python3.11/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/home/hslee/Desktop/Embedded_AI/Backbone-Neck-Self-Distillation/RetinaNet/train.py", line 28, in <module>
    import models.detection
  File "/home/hslee/Desktop/Embedded_AI/Backbone-Neck-Self-Distillation/RetinaNet/models/__init__.py", line 7, in <module>
    from . import detection
  File "/home/hslee/Desktop/Embedded_AI/Backbone-Neck-Self-Distillation/RetinaNet/models/detection/__init__.py", line 1, in <module>
    from ..retinanet import *
  File "/home/hslee/Desktop/Embedded_AI/Backbone-Neck-Self-Distillation/RetinaNet/models/retinanet.py", line 728, in <module>
    @register_model()
     ^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/envs/DL/lib/python3.11/site-packages/torchvision/models/_api.py", line 197, in wrapper
    raise ValueError(f"An entry is already registered under the name '{key}'.")
ValueError: An entry is already registered under the name 'retinanet_resnet50_fpn'.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2372661) of binary: /home/hslee/anaconda3/envs/DL/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/hslee/anaconda3/envs/DL/lib/python3.11/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/hslee/anaconda3/envs/DL/lib/python3.11/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/hslee/anaconda3/envs/DL/lib/python3.11/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/hslee/anaconda3/envs/DL/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/hslee/anaconda3/envs/DL/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/envs/DL/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-30_02:07:25
  host      : hslee-desktop
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2372661)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
